repos:
  # Ruff: lint + import sorting (keeps formatting to Black)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Black: code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # mypy: type-check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests==2.32.*