FROM mambaorg/micromamba:1.5.10-jammy AS base

ENV MAMBA_DOCKERFILE_ACTIVATE=1
WORKDIR /app

COPY environment.yml /tmp/environment.yml
RUN micromamba create -y -f /tmp/environment.yml && micromamba clean -a -y

ARG ENV_NAME=sme310
ENV CONDA_DEFAULT_ENV=${ENV_NAME}
ENV PATH=/opt/conda/envs/${ENV_NAME}/bin:$PATH

# copy your code
COPY . .

EXPOSE 8000
CMD ["uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
