name: sme310
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  # Core/runtime & infra (conda)
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch=2.5.1=*cpu_generic*
  - uvicorn=0.35.0
  - uvicorn-standard=0.35.0
  - fastapi=0.116.2
  - starlette
  - httpx=0.28.1
  - anyio
  - h11
  - httpcore=1.0.9
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - yarl
  - attrs
  - charset-normalizer
  - idna
  - urllib3=2.5.0
  - certifi
  - click=8.2.1
  - colorama
  - jinja2
  - markupsafe
  - python-dateutil
  - pytz
  - tzdata
  - pyarrow
  - pillow
  - requests=2.32.5
  - filelock
  - fsspec
  - cachetools
  - greenlet
  - networkx
  - sympy
  - sqlalchemy=2.0.43
  - orjson
  - regex
  - jsonschema
  - jsonschema-specifications
  - referencing
  - rpds-py
  - pluggy
  - iniconfig
  - pytest
  - watchdog
  - watchfiles
  - altair
  - pygments
  - tornado
  - typing_extensions
  - protobuf>=4.25,<5.29
  - gitdb
  - gitpython
  - smmap
  - pydeck
  - mlflow=3.2.0
  - setuptools
  - wheel
  - tqdm

  # Web server / IO extras
  - gunicorn=23.0.0
  - uvloop
  - httptools
  - websockets=15.0.1
  - websocket-client=1.8.0
  - email-validator=2.3.0
  - python-multipart
  - flask=3.1.2
  - werkzeug=3.1.3
  - docker-py=7.1.0

  # Visualization / plotting stack
  - matplotlib=3.10.6
  - contourpy
  - kiwisolver
  - fonttools

  # Security/SSH
  - bcrypt
  - pyopenssl
  - pynacl
  - paramiko

  # GraphQL items
  - graphene=3.4.3
  - graphql-core=3.2.6
  - graphql-relay=3.2.0

  # Anything that isn’t reliably on conda-forge (or you pinned very new)
  - pip:
      - openai==1.106.1
      - langchain==0.3.27
      - langchain-community==0.3.29
      - langchain-core==0.3.75
      - langchain-huggingface==0.3.1
      - langchain-openai==0.3.32
      - langchain-pinecone==0.2.12
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.25
      - transformers==4.49.0
      - tokenizers==0.21.1
      - tiktoken==0.11.0
      - sentence-transformers==5.1.0
      - pinecone==7.3.0
      - pinecone-plugin-assistant==1.8.0
      - pinecone-plugin-interface==0.0.7
      - safetensors==0.5.3
      - simsimd==6.5.2
      - narwhals==2.3.0
      - propcache==0.3.2
      - jiter==0.10.0
      - python-dotenv==1.1.1
      - requests-toolbelt==1.0.0
      - streamlit==1.49.1
      - aiohttp-retry==2.9.1
      - hf-xet==1.1.10
      - httpx-sse==0.4.1
      - huggingface-hub==0.35.0
      - rich==14.1.0
      - rich-toolkit==0.15.1
      - ruff==0.13.0