name: sme310
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.10
  - pip
  # Core/runtime & infra (conda)
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch=2.5.1=*cpu_generic*
  - uvicorn
  - fastapi
  - starlette
  - httpx
  - anyio
  - h11
  - httpcore
  - aiohttp
  - aiosignal
  - yarl
  - attrs
  - charset-normalizer
  - idna
  - urllib3
  - certifi
  - click
  - colorama
  - jinja2
  - markupsafe
  - python-dateutil
  - pytz
  - tzdata
  - pyarrow
  - pillow
  - requests
  - filelock
  - fsspec
  - cachetools
  - greenlet
  - networkx
  - sympy
  - sqlalchemy
  - orjson
  - regex
  - jsonschema
  - jsonschema-specifications
  - referencing
  - rpds-py
  - pluggy
  - iniconfig
  - pytest
  - watchdog
  - altair
  - pygments
  - tornado
  - typing_extensions
  - protobuf>=4.25,<5.29
  - gitdb
  - gitpython
  - smmap
  - pydeck
  - mlflow
  - setuptools
  - wheel
  - tqdm
  # Anything that isn’t reliably on conda-forge (or you pinned very new)
  - pip:
      - openai==1.106.1
      - langchain==0.3.27
      - langchain-community==0.3.29
      - langchain-core==0.3.75
      - langchain-huggingface==0.3.1
      - langchain-openai==0.3.32
      - langchain-pinecone==0.2.12
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.25
      - transformers==4.49.0
      - tokenizers==0.21.1
      - tiktoken==0.11.0
      - sentence-transformers==5.1.0
      - pinecone==7.3.0
      - pinecone-plugin-assistant==1.8.0
      - pinecone-plugin-interface==0.0.7
      - safetensors==0.5.3
      - simsimd==6.5.2
      - narwhals==2.3.0
      - propcache==0.3.2
      - jiter==0.10.0
      - python-dotenv==1.1.1
      - requests-toolbelt==1.0.0
      - streamlit==1.49.1
      - aiohttp-retry==2.9.1
